### ISSUE TITLE
Can be a drop-in replace for the official fzf.vim plugin?

### ISSUE THREAD

**Issue by Mte90** [vijaymarupudi/nvim-fzf#10]
Just asking because various plugin integrates with that and will simplify the migration to pure lua stuff.

**Comment by vijaymarupudi** [comment]
Currently, this plugin is not an API compatible drop-in replacement.

Do you mean reimplement the fzf.vim API in lua? Or provide a vim interface that looks like the fzf.vim api?

If the first, I could see that being useful, but a lot of things in the fzf.vim are redundant in lua, for e.g. lua does not need dict function, so the reimplementation would be a subset (but a very useful subset) of the API.

If it's the second, I don't think it'll be too useful, I think most nvim usage should be in lua, so I will welcome contributions, but not implement it myself.

**Comment by vijaymarupudi** [comment]
Closing until further updates
