### ISSUE TITLE
nvim-fzf doesn't respect fzf options set from neovim

### ISSUE THREAD

**Issue by monkoose** [vijaymarupudi/nvim-fzf#12]
There is environment variable `$FZF_DEFAULT_OPTS`, that you can change for your neovim only with `let $FZF_DEFAULT_OPTS = ...` inside your `init.vim/init.lua`, but currently for some reason nvim-fzf doesn't respect this option and uses global environment variable.

The problem:
I don't want my fzf look and behave the same in my terminal and my editor. Currently the most annoying setting is `--height=40%` in my global environment variable, that just shrink visible area of fzf inside neovim.

**Edited:** README actually mentions about this environment variable and that it respects it. But it doesn't work for me.

Ways to reproduce:
Set `$FZF_DEFAULT_OPTS` in your shell to something.
`let $FZF_DEFAULT_OPTS = ''` in your init.vim (or `:let $FZF_DEFAULT_OPTS = ''` in command-line) but nvim-fzf will still uses global environment variable.

**Comment by monkoose** [comment]
It's like the same steps to reproduce, like you did:( Do you know in which direction i can dig? It worked fine with fzf.vim.

**Comment by vijaymarupudi** [comment]
Good to know that this can happen, if this is a common point of confusion I might switch to hardcoding `/bin/sh` as the shell in the future. That has caveats for potential future Windows support, so holding off for now.
