### ISSUE TITLE
Add option to specify custom border chars

### ISSUE THREAD

**Issue by ibhagwan** [vijaymarupudi/nvim-fzf#13]
Can you please add the option to add custom border chars to be passed to `nvim_open_win` at [https://github.com/vijaymarupudi/nvim-fzf/blob/master/lua/fzf/floating_window.lua#L22]?

Can set the default to: `borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' }`.

I can then add passthrough to it in my code and close [this issue](https://github.com/ibhagwan/fzf-lua/issues/5) in my plugin.

**Comment by gegoune** [comment]
Default of `border` parameter of `nvim_open_win` is `none`, just in case you would like to keep the default. I will be overriding it anyway so default makes no difference to me, just though I would mention it.

**Comment by vijaymarupudi** [comment]
Quoting from recent commit https://github.com/vijaymarupudi/nvim-fzf/commit/b523a51df9794a3b524a8d07af967e39262e0d7f

  * `window_options.border` (boolean | string | table, default: true): whether to display a border
    * if `border` is `false`, a border won't be shown
    * if `border` is `true`, a rounded border will be shown
    * if `border` is anything else, it is passed directly to
      `nvim_open_win`

This should fix this! Appreciate the work being doing in `fzf-lua` :)
