### ISSUE TITLE
Commands implementations 

### ISSUE THREAD

**Issue by cloggier** [vijaymarupudi/nvim-fzf#2]
That's great!

Entry point seems rather difficult for average user though (see example of Helptags which requires quite a lot of knowledge to come up with something like that). Are you planning to provide implementations for commands provided by fzf.vim plugin or is it beyond the scope?

**Comment by cloggier** [comment]
Frankly I did think about it while composing previous message. It makes sense and having two plugins is not really a problem for end user. Thanks for your response.

**Comment by vijaymarupudi** [comment]
You're welcome! The repository to use or contribute to can be found here <https://github.com/vijaymarupudi/nvim-fzf-commands>
