### ISSUE TITLE
Passing `--select-1` to fzf CLI argument does not work as expected

### ISSUE THREAD

**Issue by fanliver** [vijaymarupudi/nvim-fzf#21]
Information about the fzf `--select-1` argument:
>        -1, --select-1
>              Automatically select the only match

My code:
```
local fzf = require("fzf")

coroutine.wrap(function()
    local result = fzf.fzf({"choice 1"},  "--select-1")
  if result then
    print(result[1])
  end
end)()
```
Above is my simple code to test the behavior when `--select-1` is passed to fzf.
I would expect the vim floating window not to display at all because there is only one item to select.
However, running this code displayed a floating window and then close it immediately. 

Does `nvim-fzf` support returning the auto-selected item without displaying a new floating window?

**Comment by vijaymarupudi** [comment]
I think this is impossible to detect this before launching fzf, so this is not supported by the default `fzf.fzf` function. However, you can roll your own by running `fzf.raw_fzf()` in a background buffer, waiting for a short timeout, and then displaying the buffer in a floating window, only if the fzf process did not end.

**Comment by ibhagwan** [comment]
I also gave up on this idea, honestly not a big deal, in `fzf-lua` I run all lsp functions asynchronously, thus I had a similar issue when having to jump to a location in `lsp_references` and `lsp_definitions` when the result set was a single match,  I worked around it by manually closing the fzf window with `nvim_close_win` as you can see in [lsp.lua#L20](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/lsp.lua#L20)

**Comment by vijaymarupudi** [comment]
Another technique one can perform is to run the fzf process in non-interactive mode, check if there's only one result, and if not, then use `nvim-fzf` to display the interactive finder. Unless the result list is enormous, I can see this working pretty well.

**Comment by vijaymarupudi** [comment]
I'm going to close this issue, some workarounds have been suggested already.
