### ISSUE TITLE
[Feature Request] async raw_action to feed `change:reload` events

### ISSUE THREAD

**Issue by ibhagwan** [vijaymarupudi/nvim-fzf#23]
When using `fzf` with `change:reload:'nvim-fzf action string' {q}` the function forces the UI to wait until it's done before releasing the UI back to the user.

It's a bit hard to understand without a real-life scenario so I'll explain:
If you look at [fzf-lua issue #44](https://github.com/ibhagwan/fzf-lua/issues/44) the user requested a functionality where fzf is only being used as a selector and every keystroke sends a new `workspace/symbol` request to the LSP server and re-populates the list (basically `live_grep` but for LSP workspace symbols).

You can see my implementation of this action at [lsp.lua#L495](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/lsp.lua#L495), basically what happens is that when `opts.async = false`, `set_lsp_fzf_fn` will set `opts.fzf_fn` to a table containing the LSP results (vs set to a function with a coroutine when `async = true`).

This isn't optimal as every keystroke generates a new LSP query, waits for it to finish and only then returns the results to `fzf` which can cause delays and undesirable UI behavior.

What I'd like to do is populate fzf asynchronously as I do on the initial query, if you look at [lsp.lua#L174](https://github.com/ibhagwan/fzf-lua/blob/main/lua/fzf-lua/providers/lsp.lua#L174) you can see the asynchronous function which is set when `async = true` which is then used by `nvim-fzf` to populate the LSP results, optimally I'd like to have an interface where I can use the same function on both the initial query and the reload query.

Hope this is clear enough.

**Comment by vijaymarupudi** [comment]
I see, I'm not sure why the current async action would be blocking... could you make a minimal example, maybe using `sleep` to show me what happens? I don't use LSP, so I can't really replicate the issue.

**Comment by ibhagwan** [comment]
I’ll send you one tomorrow but regardless there is no way with the current action to send results one by one, just imagine a `seq 1000` blocking or not you can’t send the numbers to nvim-fzf one by one which what I’m after, in the current implementing you have to accumulate all the results and send them back as a table.

What I’m after is similar functionality to sending nvim-fzf a function and then using the callback to send items one by one.

**Comment by vijaymarupudi** [comment]
Ah, isn't that what `require("fzf.actions").raw_async_action(fn)` helps with?

**Comment by ibhagwan** [comment]
Oh, I totally missed you added this function [13 days ago](https://github.com/vijaymarupudi/nvim-fzf/commit/fe114ad9c7a8ec679c433dd52c5fa2f8444b464f#diff-4d59b931bff1869899aad343debb3c9c9cc05349b94503e516d33bb1ceb96cfd)

This should solve it I hope!

**Comment by vijaymarupudi** [comment]
Ah I see! Yep, it was in response to the async shell command in preview request. I decided to make a domain general solution, looks like it'll help here too :)
