### ISSUE TITLE
broken fzf preview with aliased nvim

### ISSUE THREAD

**Issue by ucan35** [vijaymarupudi/nvim-fzf#25]
Hi, it seems using fzf previews with an aliased nvim command can break since aliases are not expanded in non-interactive shells.

Because the distro I'm using does not ship latest neovim, I'm using extracted neovim appimage from a custom directory. I have my nvim command aliased to run the relevant binary under this directory.

E.g the extracted appimage is located under `~/Projects/nvim-5/squashfs-root/` and nvim is aliased to `~/Projects/nvim-5/squashfs-root/AppRun`. 

The [command](https://github.com/vijaymarupudi/nvim-fzf/blob/8905eeea65b5b92ce0eff434a016e7e2fb4a615d/lua/fzf/actions.lua#L23) `nvim --headless --clean --cmd %s %s %s {+}` fails at [vim.fn.termopen](https://github.com/vijaymarupudi/nvim-fzf/blob/8905eeea65b5b92ce0eff434a016e7e2fb4a615d/lua/fzf.lua#L118) saying `Error detected while processing pre-vimrc command line` since the distro shipped version of my neovim is 0.4.

I can workaround this by replacing `nvim --headless --clean --cmd %s %s %s {+}` string with the expanded alias. I have thought to call `alias nvim` and feed the result into command like below but this is inefficient since there might be recursive aliases or none at all. If only I could invoke `alias_expand_line` programmatically.
```lua
local vim_cmd = vim.fn.system('alias nvim')
local action_string = string.format(vim_cmd .. " --headless --clean --cmd %s %s %s {+}",
```

The example that breaks for me.
```lua
local fzf = require "fzf".fzf
local action = require "fzf.actions".action

coroutine.wrap(function()
  -- items is a table of selected or hovered fzf items
  local shell = action(function(items, fzf_lines, fzf_cols)
    -- only one item will be hovered at any time, so get the selection
    -- out and convert it to a number
    local buf = tonumber(items[1])

    -- you can return either a string or a table to show in the preview
    -- window
    return vim.api.nvim_buf_get_lines(buf, 0, -1, false)
  end)

  fzf(vim.api.nvim_list_bufs(), "--preview " .. shell)
end)()
```

![image](https://user-images.githubusercontent.com/6537153/129974857-21c6bc40-dc0f-4478-8c24-0084315d080b.png)

Would you have any solution/suggestion for this?

Note: to overcome config issues, the real alias I use is `env XDG_CONFIG_HOME=~/Projects/nvim-5/config ~/Projects/nvim-5/squashfs-root/AppRun -u ~/Projects/nvim-5/config/nvim/init.lua`.

**Comment by vijaymarupudi** [comment]
I doubt your suggested fix is inefficient, personally. It is only resolved once per command (not every preview), and I suspect that's the sort of thing shells would be pretty fast at.

Do you notice a lag with your fix? If not, I'm willing to merge it.

**Comment by ucan35** [comment]
The problem with `vim.fn.system('alias nvim')` is this is non-interactive, again. So this would not be able to resolve aliases for nvim since aliases are loaded from `rc` files for *interactive* shells.

I'm tinkering about other possibilities like maybe we could obtain program arguments from vim itself but this does not seem a good approach to me. Maybe best could be setting up an optional `g:FZF_VIM_CMD` variable to enable custom nvim commands.

**Comment by s-taylor** [comment]
I seem to be having the same issue, I'm using the neovim appimage on ubuntu on WSL.

**Comment by vijaymarupudi** [comment]
Got it, @s-taylor and @ucan35, can you post the output of the `echo v:argv` command? I think getting the path of the executable that way will work well.

**Comment by ucan35** [comment]
That seems plausible! Only thing that's left out is environment settings, but since the environment variables are inherited by child process, they should be fine. If there aren't  any harmful options that could kill fzf's preview command I think this could be the way to go.
```
:echo v:argv
['/home/can/Projects/nvim-5/squashfs-root/usr/bin/nvim', '-u', '/home/can/Projects/nvim-5/config/nvim/init.lua', '-b']
```

**Comment by vijaymarupudi** [comment]
Great! I'll wait for @s-taylor to respond, and then I'll implement the fix if it'll fix it for both of you!

**Comment by s-taylor** [comment]
@vijaymarupudi `['/tmp/.mount_nvim.aBoY47f/usr/bin/nvim']`

**Comment by vijaymarupudi** [comment]
@s-taylor, can you try to run the nvim using the path from `:echo v:argv` in a different terminal while the first instance is still running. I want to ensure that this will fix the issue.

**Comment by s-taylor** [comment]
:echo v:argv is ['/tmp/.mount_nvim.azNS0H2/usr/bin/nvim']

I also rechecked my other terminal and the value is now different to what i posted before. I'm wondering if it extracts the appimage each time you launch it or something?

**Comment by vijaymarupudi** [comment]
I hope the latest commit fixes the issue. Let me know if it works!
