### ISSUE TITLE
What are the highlight groups for the floating window?

### ISSUE THREAD

**Issue by mhanberg** [vijaymarupudi/nvim-fzf#26]
Hi!

I am trying to use nvim-fzf, and am seeing some higlight issues that I don't see with fzf.vim.

This is what I see with fzf.vim, which is what I want.
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/5523984/130108939-00041de3-fe76-4ec1-8483-f73713072296.png">

This is what I see with nvim-fzf

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/5523984/130109156-824725ca-4208-49e5-97ef-7f9692cbaedd.png">

In the docs it says to use the `on_window_create` callback to configure things like the background highlight, but I'm not sure what highlight group to configure.

Thanks!

**Comment by vijaymarupudi** [comment]
By default, `nvim-fzf` uses the default floating window background color, which is a window-local `Normal` highlight group set to `NormalFloat`. You can change this to the typical window background using something like this;

```lua
require("fzf").default_options = {
  window_on_create = function()
    vim.cmd("set winhl=Normal:Normal")
  end
}
```

**Comment by mhanberg** [comment]
Thanks!
