### ISSUE TITLE
Error executing lua: [string "<nvim>"]:8: attempt to call local 'usr_func' (a nil value)

### ISSUE THREAD

**Issue by ibhagwan** [vijaymarupudi/nvim-fzf#28]
First appeared in [fzf-lua issue #71](https://github.com/ibhagwan/fzf-lua/issues/71).

Not really sure what causes that, there is another discussion going on in that issue so it's better we discuss this here.

The user is using `nix` to install neovim, here's his `--version` output:
```sh
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by _nixbld1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/1vwl16nna73ca7h4f9bgv3556343nqf0-neovim-unwrapped-0.5.0/share/nvim
"

Run :checkhealth for more info
```

It appears that `get_func` inside registry.lua is returning nil, I'm not sure what could cause that to happen but perhaps it has something to do with the redefinition of the `counter` var as both a file local var as well as a function parameter, I have the same  LuaJIT version so I'm not sure why that would work for almost everyone and not here, might be a totally different issue.

https://github.com/vijaymarupudi/nvim-fzf/blob/7c06b1ef15be6b7f9a24439025e095cadbee0669/lua/fzf/registry.lua#L13

**Comment by vijaymarupudi** [comment]
I'm struggling to find a cause, if the user can print the contents of registry when it's accessed, along with when a function is stored in the registry, that might help, but yeah, I'm stumped.

**Comment by ibhagwan** [comment]
> I'm struggling to find a cause, if the user can print the contents of registry when it's accessed, along with when a function is stored in the registry, that might help, but yeah, I'm stumped.

The user is already using the old native bat previewer where the command is supplied to fzf directly and the action is only used to extract the filename from the entry.

@ahmedelgabri - will you be able/willing to reproduce the error by using the default previewer and work with @vijaymarupudi to find the source of the problem?

**Comment by ahmedelgabri** [comment]
@vijaymarupudi let me know in which lines you want me to add the `print` statements & I will do this.

**Comment by ibhagwan** [comment]
Alright @vijaymarupudi, we got some progress, see the below two comments to understand the issue. In short, it seems that `nvim-fzf` has an issue when nvim is run with a custom `NVIM_LISTEN_ADDRESS`.

@ahmedelgabri wrote:

> Ok, I think it's related to nvr if I run vanilla command nvim it works fine, it I run it like this NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim (which is my default alias) then all problems start to happen.

He also provided a screen capture (if it would help) [here](https://github.com/ibhagwan/fzf-lua/issues/71#issuecomment-909579454).

**Comment by ibhagwan** [comment]
And here lies the crux of the issue:

https://github.com/vijaymarupudi/nvim-fzf/blob/7c06b1ef15be6b7f9a24439025e095cadbee0669/action_helper.lua#L45

**Comment by vijaymarupudi** [comment]
I see, that's interesting, because communicating with that listen address should still work. Atleast it does on my machine. We need to  add this line at L14 of registry.lua and check if it prints. If it does print, then it means that the action helper is able to talk to the main neovim instance. If not, then we need to determine why the NVIM_LISTEN_ADDRESS is not being forwarded to the child process properly, or if connecting to the socket is erroring out.

```lua
print("NVIM_FZF", counter)
```

**Comment by ibhagwan** [comment]
> I see, that's interesting, because communicating with that listen address should still work. Atleast it does on my machine. We need to add this line at L14 of registry.lua and check if it prints. If it does print, then it means that the action helper is able to talk to the main neovim instance. If not, then we need to determine why the NVIM_LISTEN_ADDRESS is not being forwarded to the child process properly, or if connecting to the socket is erroring out.
> 
> I'm a bit skeptical of blaming nvr just yet, because a named socket should be able to accept multiple clients.
> 
> ```lua
> print("NVIM_FZF", counter)
> ```

Look at the screen capture from @ahmedelgabri, nvim can actually communicates to that address only that it appears to be the address of the remote nvim. Look what happens at the end of the capture, it has two fzf-lua instances (connected through nvr I would assume), when you change files on the right side, the preview action is actually sent to the remote nvim instance and the preview appears on the remote nvim.

**Comment by vijaymarupudi** [comment]
Sorry about that, I completely missed the last part of the screen capture! @ahmedelgabri, please ignore the print statement.

That is some remarkable effort, thank you very much! The problem is the lack of randomized `$NVIM_LISTEN_ADDRESS` for each instance.

https://github.com/vijaymarupudi/nvim-fzf/commit/d811ae553ec83c19941b187a8ac2fee9529cf9e3 should fix the issue!

Really appreciate the well described bug reports by both @ahmedelgabri  and @ibhagwan, I've truly got some of the best users :)

**Comment by ibhagwan** [comment]
Great looking solution, now we just have to wait for @ahmedelgabri to confirm it's working.

**Comment by ahmedelgabri** [comment]
Thanks @vijaymarupudi it's working fine now 👍🏼

**Comment by vijaymarupudi** [comment]
Great, good to hear!
