### ISSUE TITLE
Selecting an item makes preview action send selected item and not highlighted item

### ISSUE THREAD

**Issue by ibhagwan** [vijaymarupudi/nvim-fzf#29]
See [fzf-lua issue #102](https://github.com/ibhagwan/fzf-lua/issues/102) for more info.

I was able to easily reproduce this bug with the below minimal function, notice that once you select an item with `<Tab>` and then move the cursor the preview will keep showing the selected item vs the highlighted item:

```lua
M.test = function()
  local fzf = require("fzf").fzf
  local action = require("fzf.actions").action
  local act = action(function(args)
    local objects = vim.tbl_map(vim.inspect, { args })
    print(unpack(objects))
    return(unpack(objects))
  end)
  coroutine.wrap(function()
    fzf({1, 2, 3, 4}, "--multi --preview-window=nohidden:down:50% --preview=" .. act)
  end)()
end
```

Notice in the below image I have item `2` selected and item `4` highlighted, however the action arguments still point to item `2`:
![screenshot-1630811977](https://user-images.githubusercontent.com/59988195/132113759-ab50f35a-ba34-4c9c-9e39-40c0ee3820f4.png)

**Comment by vijaymarupudi** [comment]
Isn't this just an upstream fzf thing? Here's the shell example

```bash
seq 1 4 | fzf --preview="echo {+}" --multi
```

**Comment by vijaymarupudi** [comment]
Here's what you need:

```
seq 1 4 | fzf --preview="echo {} {+}" --multi
```

**Comment by ibhagwan** [comment]
> Here's what you need:
> 
> ```
> seq 1 4 | fzf --preview="echo {} {+}" --multi
> ```

Oops, can’t believe I didn’t think to check that :)

Ty!
