### ISSUE TITLE
nvim-fzf does not utilize full height of window contrary to fzf

### ISSUE THREAD

**Issue by alexanderjeurissen** [vijaymarupudi/nvim-fzf#3]
### Context

there seems to be a odd discrepancy in the way `nvim-fzf` populates buffers with results compared to the default `fzf` vim implementation.

Somehow nvim-fzf does not utilize the full height when drawing the lines, however when using ctrl+n one can scroll the complete list.

First I thought this might be caused by the `floating window` implementation, but the behavior can be replicated in split windows as well as the use_current_window.

### command / config

I use a custom floating window function which utilizes a different height and background color, however I was able to reproduce the bug with aforementioned display options.

in both cases the following command is used as input:

`rg --files --ignore --smart-case --hidden --follow --no-messages --ignore-file ~/.gitignore`

below is the configuration for both lua / vim versions:

*in the default vim implementation that ships with fzf:* 

```vim
let g:fzf_default_options = '--inline-info --multi --sort --layout=reverse --bind=ctrl-a:select-all,ctrl-d:deselect-all'
let g:fzf_layout = { 'window': 'call general#create_centered_window()' }
```

*in nvim-fzf:*

```lua
coroutine.wrap(function()
  local win = vim.api.nvim_get_current_win()
  local b1, b2 = unpack(vim.fn["general#create_centered_window"]())

  local FILES_CMD = 'rg --files --ignore --smart-case --hidden --follow --no-messages --ignore-file ~/.gitignore'
  local DEFAULT_OPTS = table.concat({
    '--inline-info',
    '--multi',
    '--sort',
    '--layout=reverse',
    '--bind=ctrl-a:select-all,ctrl-d:deselect-all',
    '--expect=ctrl-o'
  }, ' ')

  local results = fzf.raw_fzf(FILES_CMD, DEFAULT_OPTS)

  vim.cmd("bw! " .. b1)
  vim.cmd("bw! " .. b2)
  vim.api.nvim_set_current_win(win)

  vim.cmd('edit' .. vim.loop.cwd() .. '/' .. results[2])
end)()
```

### Differences

Below are two screenshots of fzf / nvim-fzf respectively.

*The default vim implementation that ships with fzf:* 
<img width="1792" alt="Screen Shot 2021-03-08 at 9 34 01 PM" src="https://user-images.githubusercontent.com/1220084/110380004-d345a900-8057-11eb-915b-0f2852f329b0.png">

*nvim-fzf:*
<img width="1792" alt="Screen Shot 2021-03-08 at 9 33 54 PM" src="https://user-images.githubusercontent.com/1220084/110379994-d17be580-8057-11eb-9122-178baa04d896.png">

**Notable differences:**

1. The prompt is different although that might very well be due to the default vim bindings that fzf uses
2. the vim implementation that ships with fzf utilizes the complete buffer height when drawing

**Comment by alexanderjeurissen** [comment]
Found the issue, it seems that the default vim implementation that ships with fzf does not respect the `FZF_DEFAULT_OPTS` environment variable, but `nvim-fzf` does.

I had the following default options:

```fish
 set -gx FZF_DEFAULT_OPTS '--color=bw --height 40% --reverse'
```

hence the height was not utilized as the fzf window always was limited to 40% height. The issue became clear to me when adding the `--border` option to render the actual bounds of the fzf window:

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/1220084/110382283-f7ef5000-805a-11eb-80c5-78e395b12ad5.png">

**Comment by vijaymarupudi** [comment]
What do you think is the most intuitive behavior here? Using FZF_DEFAULT_OPTS or not?

**Comment by alexanderjeurissen** [comment]
I think that after thinking about it that I actually prefer the nv-fzf behavior. It also works as expected where the local options passed override the environment variable options. 

I do think it would be nice to document this behavior somewhere.
