### ISSUE TITLE
Potential race condition bug inside `choices_to_shell_cmd_previewer`

### ISSUE THREAD

**Issue by ibhagwan** [vijaymarupudi/nvim-fzf#32]
I just solved a bug in `fzf-lua` that uses similar code to `choices_to_shell_cmd_previewer`, it might affect `nvim-fzf` so you may want to look into it.

While implementing a "remembering" `live_grep` (i.e. every keystroke gets saved so that you can continue your live search exactly where you left off), I had implemented a `raw_async_function` with code borrowed from `choices_to_shell_cmd_previewer` that runs `rg` in the background and populates the results in fzf.

While testing this I noticed that the result set would vary randomly in size and the function was returning a partial result set.

Troubleshooting the issue I discovered that `read_cb` could be called multiple times before even a single `uv.write` is complete, imagine a  print at the start of `read_cb` and at the completed callback of `uv_write`, the printout would more often than not look like this:

```sh
read_cb
uv.write
read_cb
uv.write
read_cb
read_cb
read_cb    <-- end of data
uv.write
uv.write
uv.write
```

Now let's assume that the marked `read_cb` is be the last call and would be sent with `data = nil` - that would trigger a `cleanup()` call, close the fzf pipe and the all the following `uv.write` calls would err.

Hope this makes sense over text.

Now for the solution, I implemented a simple `read_cb_count` variable and made sure that the pipe wouldn't be closed unless the last `uv.write` call is complete (i.e. `read_cb_count = 0`)

You can take a look at the code here, hopefully this would make sense after you read the code, lmk your thoughts?

https://github.com/ibhagwan/fzf-lua/blob/57ce1bff55a287ce4f66b90e8448f32b860d22cd/lua/fzf-lua/core.lua#L305-L363

**Comment by vijaymarupudi** [comment]
Thanks for the report! I've been a bit busy lately, I will get to this soon!

**Comment by ibhagwan** [comment]
No worries, take your time, I’m not getting any reports on this being broken.

**Comment by vijaymarupudi** [comment]
Finally got it, and I believe I have fixed it. Thank you so much for the well written issue, must have been pretty difficult to diagnose. Concurrency is always difficult haha.

**Comment by ibhagwan** [comment]
> Finally got it, and I believe I have fixed it. Thank you so much for the well written issue, must have been pretty difficult to diagnose. Concurrency is always difficult haha.

As long as it’s not kernel level multi thread debugging I’m happy :)

Interesting implementation, you prefer the `cleanup_request_sent` to `uv.is_closing` check? any specific reason? Does it have higher overhead than what is most likely  an internal library boolean test?

**Comment by vijaymarupudi** [comment]
> Handles that wrap file descriptors are closed immediately but callback will still be deferred to the next iteration of the event loop. It gives you a chance to free up any resources associated with the handle.

My implementation was designed under the possibility of long running processes, where people might try to close the pipe at a time where no write callback is scheduled. I think my implementation handles that edge case.

I'm not really sure about the utility of `uv.is_closing()`, I feel like one only needs it when they already close a pipe (using `uv.close()`), and then need to query whether they did that before the close callback. My implementation only calls `uv.close()` once and then never does anything after that, so I didn't think I needed it?

**Comment by vijaymarupudi** [comment]
Ah yes, that is correct, which I why I had the boolean to prevent closing twice. Yep I agree, just different implementations of the same bugfix :)
