### ISSUE TITLE
LibUV and Windows support: why not `uv.pipe_`?

### ISSUE THREAD

**Issue by cpkio** [vijaymarupudi/nvim-fzf#33]
I'd love to use `fzf-lua` in Windows, and now I'm investigating the named pipe usage options. You suggest using `CreateNamedPipe` (like `luapower/fs` does), but LibUV [declares](https://github.com/luvit/luv/blob/master/docs.md#uv_pipe_t--pipe-handle) named pipes support, so I wonder why didnt you use that.

Are there any issues I dont yet know about?

**Comment by vijaymarupudi** [comment]
Not entirely sure why I didn't notice that, but it should be good now, switched it to use that instead.

https://github.com/vijaymarupudi/nvim-fzf/commit/d87d87978a973208dcfa76ab429000e478ae3ea1
