### ISSUE TITLE
Running a sample code produces error in Windows

### ISSUE THREAD

**Issue by cpkio** [vijaymarupudi/nvim-fzf#37]
Running `luafile %` example file
```
local fzf = require('fzf')

coroutine.wrap(function()
  local result = fzf.fzf({"choice 1", "choice 2"})
  if result then
    print(result[1])
  end
end)()
```
produces this error:
`E5113: Error while calling lua chunk: r:\1.lua:8: ...a\nvim-data\site\pack\dmitriy\start\nvim-fzf\lua\fzf.lua:198: ...a\nvim-data\site\pack\dmitriy\start\nvim-fzf\lua\fzf.lua:22: bad argument #1 to 'func' (number expected, got nil)`[^1]

[^1]: BTW, this
https://github.com/vijaymarupudi/nvim-fzf/blob/679714e140ab9b5f26731c300ecbc9108d2c9fe1/lua/fzf.lua#L111
returns `nil` (LibUV says [it `Returns: 0 or fail`](https://github.com/luvit/luv/blob/master/docs.md#uvpipe_bindpipe-name)).

**Comment by cpkio** [comment]
Change fzf.lua:82 to `return ([[\\.\pipe\%s]]):format(random_filename)`, you missed the leading slash so the pipe didnt create. With this fix, FZF runs, but has no input, so there's something wrong on the way of passing `{"choice 1", "choice 2"}` to the pipe.

**Comment by vijaymarupudi** [comment]
A question about file redirection, ideally I don't want to output fzf results to a pipe, but a file. Is output redirection, like `ls > file.txt` supported in cmd.exe?

**Comment by vijaymarupudi** [comment]
For now I'm going to use a file because I think it'll unlikely the user will select enough data for the performance to matter. Will do optimizations later if necessary.

**Comment by cpkio** [comment]
Stopped by to thank you for your work and say how much I appreciate it. I've got tired of supporting my own fork of `fzf.vim` for Windows and I'm very grateful to you because you've built this plugin and I can use it out of the box in Windows. `fzf-lua` author's decision to drop Windows compatibility is unfortunate.

**Comment by vijaymarupudi** [comment]
You're welcome, thank you for your contributions that helped make it happen!
