### ISSUE TITLE
Floating window implementation can be simplified

### ISSUE THREAD

**Issue by alexanderjeurissen** [vijaymarupudi/nvim-fzf#4]
### Context

When exploring https://github.com/vijaymarupudi/nvim-fzf/issues/3 I realized that it's possible to pass the `--border` option to fzf to draw a border around the fzf frame.

```lua
coroutine.wrap(function()
  local FILES_CMD = 'rg --files --ignore --smart-case --hidden --follow --no-messages --ignore-file ~/.gitignore'
  local DEFAULT_OPTS = table.concat({
    '--inline-info',
    '--multi',
    '--sort',
    '--layout=reverse',
    '--border'
  }, ' ')

  local results = fzf.fzf(FILES_CMD, DEFAULT_OPTS)

  vim.cmd('edit' .. vim.loop.cwd() .. '/' .. results[1])
end)()
```

result:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1220084/110384115-7cdb6900-805d-11eb-8095-5d01b5e3b6bd.png">

The double border is indicative that we likely can get rid of the complex double window floating implementation we currently utilize, and simply draw a single floating window.

That way users can specify in their fzf options if they want a border or not.

### Simplified implementation in Vimscript:

```vim
" Source: https://github.com/neovim/neovim/issues/9718#issuecomment-546603628
function! nvim_fzf#create_centered_window()
    let width = min([&columns - 4, max([80, &columns - 20])])
    let height = min([&lines - 4, max([20, &lines - 10])])
    let top = ((&lines - height) / 2) - 1
    let left = (&columns - width) / 2
    let opts = {'relative': 'editor', 'row': top, 'col': left, 'width': width, 'height': height, 'style': 'minimal'}

    set winhl=Normal:Normal
    let l:buf = nvim_create_buf(v:false, v:true)
    call nvim_open_win(l:buf, v:true, opts)
    return l:buf
endf
```

result:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1220084/110383620-d7c09080-805c-11eb-828c-5e481f461e9a.png">

diff:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1220084/110384307-bc09ba00-805d-11eb-861a-0580ab32c1d8.png">

### Simplified implementation in lua

We could go one step further and move the window implementation to lua making the plugin 100% lua.

```lua
local nvim_fzf = {}

function nvim_fzf.create_centered_window()
  local columns, lines = vim.o.columns, vim.o.lines

  local width = math.min(columns - 4, math.max(80, columns - 20))
  local height = math.min(lines - 4, math.max(20, lines - 10))

  local top = ((lines - height) / 2) -1
  local left = (columns - width) / 2)

  local opts = { relative = 'editor', row = top col = left, width = width, height = height, style = 'minimal' }

  local bufnr = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_openwin(bufnr, true, opts)

  return bufnr
end
```

**Comment by vijaymarupudi** [comment]
This is excellent, thank you so much for your work. The goal is to become fully lua based indeed. Would you like to submit a pull request, or would you like me to incorporate your suggestion?

**Comment by vijaymarupudi** [comment]
Sounds good!
