### ISSUE TITLE
Add an option to remove '\n' from `uv.fs_write` calls

### ISSUE THREAD

**Issue by ibhagwan** [vijaymarupudi/nvim-fzf#42]
https://github.com/vijaymarupudi/nvim-fzf/blob/84e119698ad6adfb787437310918339727092827/lua/fzf.lua#L194

The above is what I’m talking about, I’ll explain the use case below.

For example, fzf-lua `grep` (and `live_grep`) runs a command using `uv.spawn`, due to `\n` being added by `raw_fzf`, I cannot send the raw command output (already containing `\n`) directly to the fzf pipe (using `fzf_cb` calls), instead the data must be parsed and sent line by line (after also stripping the `\n`), needless to say parsing the lines is not always very performant, especially when dealing with large datasets, not having to parse the newlines results in a major performance improvement (this also avoids the “out of memory error” that was described in [fzf-lua#185](https://github.com/ibhagwan/fzf-lua/issues/185))

Granted in such case one could simply send the command as string in `contents` but that isn’t always possible in my code for various reasons (also adds “conditional” complexity instead of always using `uv.spawn`).

Here is what I do in my code, if the output doesn’t require line by line transformation (I.e. no icons are needed for files), I simply pass the data directly to the pipe without parsing. Given that the data isn’t guaranteed to end in a new line this doesn’t work well with `raw_fzf`, effectively forcing newline parsing:

https://github.com/ibhagwan/fzf-lua/blob/b87e5da1c25abf5fa3af15b750fafb85dca433c5/lua/fzf-lua/libuv.lua#L131-L132

**Comment by vijaymarupudi** [comment]
I think this feature is long overdue! I'm planning a major refactor of the fzf.lua internals, and will provide raw_fzf_pipe, which will expose the vim.loop pipe directly, which I think will solve this issue!

**Comment by vijaymarupudi** [comment]
Okay, whoops, there is a commit that I didn't push yet, will push later today. There will be a newline, I just missed that. People who don't need newlines should use uv.write on the second argument to the callback, which will be the uv pipe.
