### ISSUE TITLE
fzf.fzf() cannot correct process fzf_cli_args

### ISSUE THREAD

**Issue by Song-Tianxiang** [vijaymarupudi/nvim-fzf#55]
reproducation steps:

1. create file `test.lua` with code
``` lua
coroutine.wrap(function()
    local result = require('fzf').fzf({'1', '2', '3', '4'}, '--prompt=haha')
    if result then
            vim.print('You sucesss')
    end
end)()

```
2. :source
3. you will get result and cannot correctly open fzf window
4. solution: add space before and after fzf_cmd_args -> fzf_cmd_args = ' ' .. fzf_cmd_args .. ' '

**Comment by vijaymarupudi** [comment]
Not sure what's going wrong, but I doubt this is the cause of the issue, I cannot reproduce it using the code you provided. For example, spaces are added in the code already

See here: https://github.com/vijaymarupudi/nvim-fzf/blob/bd095495146a2a827774ad3ad1ef0cc843b5e257/lua/fzf.lua#L96

Could you provide more information about your setup? Have you tried running it with other plugins disabled?

**Comment by Song-Tianxiang** [comment]
Sorry, I forget my setup() call. Here the fix way to reproduce:
1. `mkdir /tmp/nvim-init; cd /tmp/nvim-init; git clone https://github.com/vijaymarupudi/nvim-fzf.git`
2. create file init.lua with code:
``` lua
vim.opt.rtp:prepend('/tmp/nvim-init/nvim-fzf')

require("fzf").default_options = {
	fzf_cli_args = '--reverse',
}
```
3. create file test.lua with code:
``` lua
coroutine.wrap(function()
    local result = require('fzf').fzf({'1', '2', '3', '4'}, '--prompt=haha')
    if result then
            vim.print('You sucesss')
    end
end)()

```
4. file strueture is:
nvim-init/
├── init.lua
├── nvim-fzf
└── test.lua
4. `nvim test.lua -u init.lua`
6. `:so`  and  we cannot open fzf window

If we add a space after the "reverse" on the fourth line of init.lua, the FZF window can display normally.

So, I suspect the issue arises from the way default options and user-specified options are being concatenated, which is causing an unintended outcome.

**Comment by vijaymarupudi** [comment]
Ah I see, now this makes sense.

Just pushed https://github.com/vijaymarupudi/nvim-fzf/commit/c89b15aee136eeb4649901552da37a404415c356, please give this a shot

**Comment by Song-Tianxiang** [comment]
It works for me.

**Comment by vijaymarupudi** [comment]
Great!
