### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by Roniyahe54** [vijaymarupudi/nvim-fzf#58]
Based on the discussion in https://github.com/ibhagwan/fzf-lua/issues/85, I propose to collect the confirmation from all contributors to nvim-fzf to change from AGPL to MIT. AGPL is a difficult license insofar as some companies do not allow to even use AGPL-licenses software for back office development.

The MIT license is used by many other vim/nvim plugins, this includes fzf.vim for example.

@vijaymarupudi agreed as the maintainer to change the license away from AGPL if all contributors agree.

Please agree to a license change by replying "Agreed":
- @vijaymarupudi 
- @ibhagwan 
- @alexanderjeurissen
- @lukas-reineke 
- @jdrouhard 
- @cpkio 
- @frabjous 
- @pynappo

**Comment by cpkio** [comment]
Agreed.

**Comment by pynappo** [comment]
agreed

**Comment by ibhagwan** [comment]
Np, and Ty for taking the lead on this @Roniyahe54!

**Comment by jdrouhard** [comment]
Agreed

**Comment by vijaymarupudi** [comment]
For posterity, agreed to change to MIT

**Comment by frabjous** [comment]
Agreed.

**Comment by alexanderjeurissen** [comment]
Agreed to change license from AGL to MIT.

**Comment by lukas-reineke** [comment]
agreed :+1:

**Comment by Roniyahe54** [comment]
Thank you everyone for the quick turn around!

@vijaymarupudi we have the ok from all contributors as listed on the contributors page. I can make a PR with the license change this weekend if you want me to.

**Comment by ibhagwan** [comment]
Ty @Roniyahe54, fzf-lua license change was completed in https://github.com/ibhagwan/fzf-lua/commit/ace9968be267b034e450be4feaf6e9107bc34fbd.
