### ISSUE TITLE
Can this be installed with native Neovim package handling?

### ISSUE THREAD

**Issue by olleharstedt** [vijaymarupudi/nvim-fzf#6]
Title. Don't want to install yet another plugin manager.

**Comment by vijaymarupudi** [comment]
I'm open to adding support, however it looks like it is currently possible? From `repeat.txt`

```
Using a single plugin and loading it automatically ~

If you don't have a package but a single plugin, you need to create the extra
directory level:
	% mkdir -p ~/.local/share/nvim/site/pack/foo/start/foobar
	% cd ~/.local/share/nvim/site/pack/foo/start/foobar
	% unzip /tmp/someplugin.zip

You would now have these files:
	pack/foo/start/foobar/plugin/foo.vim
	pack/foo/start/foobar/syntax/some.vim

From here it works like above.
```


You need to create a directory in your runtimepath (the documentation prefers 'site/pack') and clone the repository in there

```bash
mkdir -p ~/.local/share/nvim/site/pack/nvim-fzf/start/
cd ~/.local/share/nvim/site/pack/nvim-fzf/start/
git clone https://github.com/vijaymarupudi/nvim-fzf
```

Let me know if this works, and I'll add documentation to the README.

**Comment by olleharstedt** [comment]
Hm, I still get 

> E492: Not an editor command: FZF                                                                                                                                                               

after doing this and restarting Neovim.

**Comment by olleharstedt** [comment]
Fugitive worked, though.

**Comment by olleharstedt** [comment]
Current file structure:

```
            
$:~/.local/share/nvim/site/pack$ ls tpope/start/fugitive/
autoload  CONTRIBUTING.markdown  doc  ftdetect  ftplugin  plugin  README.markdown  syntax
$:~/.local/share/nvim/site/pack$ ls vijaymarupudi/start/nvim-fzf/
action_helper.lua  action_helper.sh  gifs  LICENSE  lua  plugin  README.md
```

**Comment by vijaymarupudi** [comment]
`:FZF`

You might be thinking of the [`fzf.vim`](https://github.com/junegunn/fzf.vim) plugin there haha. To test this plugin, you need to run

```vim
:lua require("fzf")
```

**Comment by olleharstedt** [comment]
Ah shit. I think I'm confusing it with Ctrl-P too. >< Sorry. Closing the issue.
